version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Running build phase..."
      # Add your actual build/test/deploy commands here
artifacts:
  files:
    - '**/*'
