artifact_bucket_name = "devops-project-ayush-s3"
github_owner         = "Ayush-silicon"
github_repo          = "DevOps-Project"
github_branch        = "main"
github_token         = "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"
ami_id               = "ami-0ded8326293d3201b"
key_name             = "Devops_Proj_key"